version: "3.9"

services:
  backend:
    build:
      context: contextPath
      dockerfile: Dockerfile  
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db  
      - DB_PORT=5432
      - DB_USER=zahid  
      - DB_PASSWORD=qwerty
      - DB_NAME=postgres  
    volumes:
      - ./backend:/app
    networks:
      - app-network
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=zahid
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
  frontend:
    build:
      context: contextPath
      dockerfile: Dockerfile  
    ports:
      - "3000:3000" 
    depends_on:
      - backend 
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
    networks:
      - app-network
volumes:
  db-data:
networks:
  app-network:
    driver: bridge