name: deploy Node.js app to EC2 server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r ./backend/* ubuntu@your-ec2-ip:/home/ubuntu/backend/
          scp -o StrictHostKeyChecking=no -r ./frontend/* ubuntu@your-ec2-ip:/home/ubuntu/frontend/
          scp -o StrictHostKeyChecking=no ./backend/docker-compose.yml ubuntu@your-ec2-ip:/home/ubuntu/docker-compose.yml

      - name: Deploy on EC2
        run: |  
          ssh -o StrictHostKeyChecking=no ubuntu@your-ec2-ip << 'EOF'
            cd /home/ubuntu
            docker-compose down
            docker-compose up -d --build
          EOF 
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_IP: ${{ secrets.EC2_IP }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_NAME: ${{ secrets.DB_NAME }} 
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          REACT_APP_BACKEND_URL: ${{ secrets.REACT_APP_BACKEND_URL }}
          CONTEXT_PATH_BACKEND: ./backend
          CONTEXT_PATH_FRONTEND: ./frontend
          DOCKERFILE_BACKEND: Dockerfile
          DOCKERFILE_FRONTEND: Dockerfile
          contextPathBackend: ${{ secrets.CONTEXT_PATH_BACKEND }}
          contextPathFrontend: ${{ secrets.CONTEXT_PATH_FRONTEND }}   
          dockerfileBackend: ${{ secrets.DOCKERFILE_BACKEND }}
          dockerfileFrontend: ${{ secrets.DOCKERFILE_FRONTEND }}
          contextPath: ${{ secrets.contextPath }}
          dockerfile: ${{ secrets.dockerfile }}
          YOUR_EC2_IP: ${{ secrets.EC2_IP }}
          YOUR_EC2_USER: ${{ secrets.EC2_USER }}
          YOUR_EC2_PATH: ${{ secrets.EC2_PATH }}
          YOUR_EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          YOUR_EC2_PORT: ${{ secrets.EC2_PORT }}
          YOUR_EC2_DOCKER_COMPOSE_PATH: ${{ secrets.EC2_DOCKER_COMPOSE_PATH }}
          YOUR_EC2_DOCKER_COMPOSE_FILE: ${{ secrets.EC2_DOCKER_COMPOSE_FILE }}
          YOUR_EC2_DOCKER_COMPOSE_PROJECT_NAME: ${{ secrets.EC2_DOCKER_COMPOSE_PROJECT_NAME }}
          YOUR_EC2_DOCKER_COMPOSE_ENV_FILE: ${{ secrets.EC2_DOCKER_COMPOSE_ENV_FILE }}
          YOUR_EC2_DOCKER_COMPOSE_OVERRIDE_FILE: ${{ secrets.EC2_DOCKER_COMPOSE_OVERRIDE_FILE }}_DOCKER_COMPOSE_OVERRIDE_FILE }}  
          YOUR_EC2_DOCKER_COMPOSE_ADDITIONAL_FILES: ${{ secrets.EC2_DOCKER_COMPOSE_ADDITIONAL_FILES }}
          YOUR_EC2_DOCKER_COMPOSE_ADDITIONAL_ENV_FILES: ${{ secrets.EC2_DOCKER_COMPOSE_ADDITIONAL_ENV_FILES }}
          YOUR_EC2_DOCKER_COMPOSE_ADDITIONAL_OVERRIDE_FILES: ${{ secrets.EC2_DOCKER_COMPOSE_ADDITIONAL_OVERRIDE_FILES }}
          YOUR_EC2_DOCKER_COMPOSE_PROJECT_ENV_FILE: ${{ secrets.EC2_DOCKER_COMPOSE_PROJECT_ENV_FILE }}
          YOUR_EC2_DOCKER_COMPOSE_PROJECT_OVERRIDE_FILE: ${{ secrets.EC2_DOCKER_COMPOSE_PROJECT_OVERRIDE_FILE }}
          YOUR_EC2_DOCKER_COMPOSE_PROJECT_ADDITIONAL_FILES: ${{ secrets.EC2_DOCKER_COMPOSE_PROJECT_ADDITIONAL_FILES }}
          YOUR_EC2_DOCKER_COMPOSE_PROJECT_ADDITIONAL_ENV_FILES: ${{ secrets.EC2_DOCKER_COMPOSE_PROJECT_ADDITIONAL_ENV_FILES }}
          YOUR_EC2_DOCKER_COMPOSE_PROJECT_ADDITIONAL_OVERRIDE_FILES: ${{ secrets.EC2_DOCKER_COMPOSE_PROJECT_ADDITIONAL_OVERRIDE_FILES }}
          YOUR_EC2_DOCKER_COMPOSE_PROJECT_NAME_ENV_FILE: ${{ secrets.E  C2_DOCKER_COMPOSE_PROJECT_NAME_ENV_FILE }}
          YOUR_EC2_DOCKER_COMPOSE_PROJECT_NAME_OVERRIDE_FILE: ${{ secrets.EC2_DOCKER_COMPOSE_PROJECT_NAME_OVERRIDE_FILE }}
          YOUR_EC2_DOCKER_COMPOSE_PROJECT_NAME_ADDITIONAL_FILES: ${{ secrets.EC2_DOCKER_COMPOSE_PROJECT_NAME_ADDITIONAL_FILES }}
          YOUR_EC2_DOCKER_COMPOSE_PROJECT_NAME_ADDITIONAL_ENV_FILES: ${{ secrets.EC2_DOCKER_COMPOSE_PROJECT_NAME_ADDITIONAL_ENV_FILES }}
          YOUR_EC2_DOCKER_COMPOSE_PROJECT_NAME_ADDITIONAL_OVERRIDE_FILES: ${{ secrets.EC2_DOCKER_COMPOSE_PROJECT_NAME_ADDITIONAL_OVERRIDE_FILES }}
